### ISSUE TITLE
Questions regarding patient generated data

### ISSUE THREAD

**Issue by JoeValentine** [department-of-veterans-affairs/health-apis-patient-generated-data#86]
@cilestin @gileswells @wyattwalter @charleystran @brentschneider - All, Hi, my name is Joe Valentine.  I have been tasked with setting up a prototype Db with medical device data that can be used in conjunction with eScreening. Angela Gant-Curtis gave me a link to your Git repo. My questions are high level at this point.  

1. It sounds as if this can be used as a collection point for patient devices, such as CPAP, Glucose devices, other medical devices from the vet/patient themselves.  Is my understanding correct? 
2. If so, do you have technical information on how this would work? I am just now starting to go through the readme files here in Git.
3. Is there specific items here that I should look at that illustrate how this all works?  Your attention to my questions is greatly appreciated.  Thanks!

**Comment by jblefkove-va** [comment]
This is a [Lighthouse](https://developer.va.gov) API that implements create, read, and update operations for [FHIR](http://hl7.org/fhir/r4/) R4 resources; currently Questionnaire, QuestionnaireResponse, and Observation are supported.

Documentation in this repo is sparse at the moment, but the OpenAPI specification is available for the sandbox environment here: https://sandbox-api.va.gov/services/pgd/v0/r4/openapi.json 

If I understand correctly, you want to collect and store observation resources? Are you looking to start using this API in sandbox? (If you have access to Lighthouse slack, let's continue the discussion [here](https://lighthouseva.slack.com/archives/CMT4MFPS6).)
